package de.afbb.bibo.ui;

public enum IconType {
	USER_MANAGE, BOOK_GROUP, BOOK_DAMAGED, BOOK_LENT, BOOK_AVAILABLE, BOOK, CD, LOGIN, PUPIL, TEACHER, USER, ARROW_UP, ARROW_DOWN, PLUS,
	MINUS, SAVE, LOGO, MEDIA, HELP, USER_MANAGE_ADD, BOOK_ADD, BOOK_GROUP_ADD, CD_ADD, TEACHER_ADD, PUPIL_ADD
}
